# ==========================================
# JEKYLL SITE CONFIGURATION
# ==========================================

theme: jekyll-theme-chirpy

# LANGUAGE & TIMEZONE
lang: en
timezone: Europe/Amsterdam

# ==========================================
# SITE INFORMATION (SEO & Display)
# ==========================================

title: Portfolio - Boas-Bas van der Veen

tagline: Third-year Game Programming student at Breda University of Applied Sciences

description: >-
  Portfolio showcasing game development projects and technical blog posts by Boas-Bas van der Veen.

url: "https://boazbaaz.github.io"

github:
  username: BoazBaaz

social:
  name: Boas-Bas van der Veen
  email: boas.bas@gmail.com
  links:
    - https://www.linkedin.com/in/boas-bas-van-der-veen/
    - https://github.com/BoazBaaz
    - https://boazbaaz.itch.io/

# ==========================================
# APPEARANCE
# ==========================================

theme_mode: dark

avatar: /assets/img/profile_picture_sqr.jpg

# ==========================================
# FEATURES
# ==========================================

toc: true

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-redirect-from

pwa:
  enabled: true
  cache:
    enabled: true

paginate: 10

baseurl: ""

# ==========================================
# COLLECTIONS
# ==========================================
collections:
  tabs:
    output: true
    sort_by: order
  projects:
    output: true
    sort_by: date
    permalink: /projects/:title/

# ==========================================
# DEFAULT SETTINGS
# ==========================================
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      toc: true
      permalink: /posts/:title/
  - scope:
      path: ""
      type: projects
    values:
      layout: project
      toc: false
      permalink: /projects/:title/
  - scope:
      path: ""
      type: tabs
    values:
      layout: page
      permalink: /:title/

# ==========================================
# BUILD SETTINGS
# ==========================================

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

exclude:
  - "*.gem"
  - "*.gemspec"
  - docs
  - tools
  - README.md
  - LICENSE
  - "package*.json"



# ==========================================
# MARKDOWN SETTINGS
# ==========================================

kramdown:
  footnote_backlink: "&#8617;&#xfe0e;"
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1
